/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appgestionstagaire;

import date_acces_object.chief_data_acces;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import module.candidat;
import module.stage;

/**
 *
 * @author User
 */
public class espace_chiefstage extends javax.swing.JFrame {

    /**
     * Creates new form espase_chiefstage
     */
    public String chief_email;

    public espace_chiefstage() {
        initComponents();
        btnadd.setEnabled(false);
        txtnom.setEditable(false);
        txtprenom.setEditable(false);
        txtemail.setEditable(false);

    }

    public espace_chiefstage(String email) {
        initComponents();
        chief_email = email;
        btnadd.setEnabled(false);
        btnchoose.setEnabled(false);
        btnadd.setEnabled(false);
        txtnom.setEditable(false);
        txtprenom.setEditable(false);
        txtemail.setEditable(false);
        getIntreships();
        getcandidats("", "");

    }

    public void getIntreships() {
        ArrayList<stage> intreships = chief_data_acces.getIntreships(chief_email);
        if (!intreships.isEmpty()) {
            Iterator itr = intreships.iterator();
            while (itr.hasNext()) {
                stage s = (stage) itr.next();
                String title = s.getTitle();
                stagess.addItem(title);
            }

        }

    }

    public void getcandidats(String stg, String nomcandidat) {
        DefaultTableModel df = (DefaultTableModel) tab.getModel();
        df.setRowCount(0);
        ArrayList<candidat> candidats = chief_data_acces.getcandidat(chief_email, stg, nomcandidat);

        Iterator itr = candidats.iterator();
        while (itr.hasNext()) {
            candidat c = (candidat) itr.next();
            Vector v = new Vector();
            v.add(c.getNom());
            v.add(c.getPrenom());
            v.add(c.getNom() + "" + c.getPrenom() + "_cv.txt");
            v.add(c.getDatedubet());
            v.add(c.getEmail());
            df.addRow(v);

        }

    }

    public void valideadd() {
        String title = txttitle.getText();
        String sujet = txtsujet.getText();
        String duree = txtduree.getText();
        if (!title.isEmpty() && !sujet.isEmpty() && !duree.isEmpty()) {
            btnadd.setEnabled(true);
        } else {
            btnadd.setEnabled(false);
        }

    }

    public void validchoose() {
        String nom = txtnom.getText();
        String prenom = txtprenom.getText();
        String emailc = txtemail.getText();
        String stage_id = txtstageid.getText();
        try {
            int intValue = Integer.parseInt(stage_id);
            if (!nom.isEmpty() && !prenom.isEmpty() && !emailc.isEmpty() && !stage_id.isEmpty()) {
                btnchoose.setEnabled(true);
            } else {
                btnchoose.setEnabled(false);
            }

        } catch (NumberFormatException e) {
            btnchoose.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txttitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtduree = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtsujet = new javax.swing.JTextArea();
        btnadd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        btnchoose = new javax.swing.JButton();
        btnnoter = new javax.swing.JButton();
        btnout = new javax.swing.JButton();
        txtstageid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        stagess = new javax.swing.JComboBox<>();
        feltring = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 204, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 204, 255));
        jLabel1.setText("TITLE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 109, -1, -1));

        txttitle.setBackground(new java.awt.Color(255, 204, 255));
        txttitle.setForeground(new java.awt.Color(0, 0, 0));
        txttitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttitleKeyReleased(evt);
            }
        });
        getContentPane().add(txttitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 106, 169, -1));

        jLabel2.setForeground(new java.awt.Color(255, 204, 255));
        jLabel2.setText("DURATION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 161, -1, -1));

        txtduree.setBackground(new java.awt.Color(255, 204, 255));
        txtduree.setForeground(new java.awt.Color(0, 0, 0));
        txtduree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdureeKeyReleased(evt);
            }
        });
        getContentPane().add(txtduree, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 158, 167, -1));

        jLabel4.setForeground(new java.awt.Color(255, 204, 255));
        jLabel4.setText("SUBJET");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 210, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 204, 255));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        txtsujet.setBackground(new java.awt.Color(255, 204, 255));
        txtsujet.setColumns(20);
        txtsujet.setRows(5);
        txtsujet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsujetKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtsujet);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 238, 246, 94));

        btnadd.setBackground(new java.awt.Color(255, 204, 255));
        btnadd.setForeground(new java.awt.Color(0, 0, 0));
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnadd.setText("ADD AN INTERNSHIP");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 383, 246, 28));

        tab.setBackground(new java.awt.Color(255, 204, 255));
        tab.setForeground(new java.awt.Color(0, 0, 0));
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "first name ", "last name", "cv", "start date", "email"
            }
        ));
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tab);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 106, -1, 305));

        jLabel3.setForeground(new java.awt.Color(255, 204, 255));
        jLabel3.setText("FIRST NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 105, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 204, 255));
        jLabel5.setText("LAST NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 161, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 204, 255));
        jLabel6.setText("EMAIL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 218, -1, -1));

        txtnom.setBackground(new java.awt.Color(255, 204, 255));
        txtnom.setForeground(new java.awt.Color(0, 0, 0));
        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnomKeyReleased(evt);
            }
        });
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 102, 151, -1));

        txtprenom.setBackground(new java.awt.Color(255, 204, 255));
        txtprenom.setForeground(new java.awt.Color(0, 0, 0));
        txtprenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprenomKeyReleased(evt);
            }
        });
        getContentPane().add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 158, 151, -1));

        txtemail.setBackground(new java.awt.Color(255, 204, 255));
        txtemail.setForeground(new java.awt.Color(0, 0, 0));
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 215, 151, -1));

        btnchoose.setBackground(new java.awt.Color(255, 204, 255));
        btnchoose.setForeground(new java.awt.Color(0, 0, 0));
        btnchoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/choose.png"))); // NOI18N
        btnchoose.setText("choose this candidat");
        btnchoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchooseActionPerformed(evt);
            }
        });
        getContentPane().add(btnchoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 381, 245, -1));

        btnnoter.setBackground(new java.awt.Color(255, 204, 255));
        btnnoter.setForeground(new java.awt.Color(0, 0, 0));
        btnnoter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/noter.png"))); // NOI18N
        btnnoter.setText("mark the work of the trainees");
        btnnoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnoterActionPerformed(evt);
            }
        });
        getContentPane().add(btnnoter, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 417, 295, 50));

        btnout.setBackground(new java.awt.Color(255, 204, 255));
        btnout.setForeground(new java.awt.Color(0, 0, 0));
        btnout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnout.setText("log out");
        btnout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnout, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 436, -1, -1));

        txtstageid.setBackground(new java.awt.Color(255, 204, 204));
        txtstageid.setForeground(new java.awt.Color(0, 0, 0));
        txtstageid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtstageidKeyReleased(evt);
            }
        });
        getContentPane().add(txtstageid, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, 150, -1));

        jLabel7.setForeground(new java.awt.Color(255, 204, 255));
        jLabel7.setText("intrship id");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, -1, -1));

        stagess.setBackground(new java.awt.Color(255, 204, 204));
        stagess.setForeground(new java.awt.Color(0, 0, 0));
        stagess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stagessActionPerformed(evt);
            }
        });
        getContentPane().add(stagess, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 140, -1));

        feltring.setBackground(new java.awt.Color(255, 204, 204));
        feltring.setForeground(new java.awt.Color(0, 0, 0));
        feltring.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                feltringKeyReleased(evt);
            }
        });
        getContentPane().add(feltring, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 120, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("feltring by name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chiefstage.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String title = txttitle.getText();
        String sujet = txtsujet.getText();
        String duree = txtduree.getText();

        chief_data_acces.addStage(title, duree, sujet, chief_email);
    }//GEN-LAST:event_btnaddActionPerformed

    private void txttitleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttitleKeyReleased
        // TODO add your handling code here:
        valideadd();
    }//GEN-LAST:event_txttitleKeyReleased

    private void txtdureeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdureeKeyReleased
        // TODO add your handling code here:
        valideadd();
    }//GEN-LAST:event_txtdureeKeyReleased

    private void txtsujetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsujetKeyReleased
        // TODO add your handling code here:
        valideadd();
    }//GEN-LAST:event_txtsujetKeyReleased


    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        // TODO add your handling code here:
        int i = tab.getSelectedRow();
        TableModel model = tab.getModel();
        String first_name = String.valueOf(model.getValueAt(i, 0));
        String last_name = String.valueOf(model.getValueAt(i, 1));
        String Email = String.valueOf(model.getValueAt(i, 4));
        txtnom.setText(first_name);
        txtemail.setText(Email);
        txtprenom.setText(last_name);

        tools.openFile.open("C:\\Users\\User\\Documents\\NetBeansProjects\\APPGestionStagaire\\cv_chief_view\\" + first_name + "" + last_name + "_cv.txt");
        btnchoose.setEnabled(true);
        new stagepostuler(chief_data_acces.get_all_intreship_of_candidat(Email, first_name, chief_email)).setVisible(true);
    }//GEN-LAST:event_tabMouseClicked

    private void txtnomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyReleased
        // TODO add your handling code here:
        validchoose();
    }//GEN-LAST:event_txtnomKeyReleased

    private void txtprenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprenomKeyReleased
        // TODO add your handling code here:
        validchoose();
    }//GEN-LAST:event_txtprenomKeyReleased

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        // TODO add your handling code here:
        validchoose();
    }//GEN-LAST:event_txtemailKeyReleased

    private void btnchooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchooseActionPerformed
        // TODO add your handling code here:
        String email = txtemail.getText();
        String nom = txtnom.getText();
        int stageid = Integer.valueOf(txtstageid.getText());
        new mailpasswordinput(chief_email, email, nom, stageid).setVisible(true);

    }//GEN-LAST:event_btnchooseActionPerformed

    private void btnoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new logIn().setVisible(true);
    }//GEN-LAST:event_btnoutActionPerformed

    private void btnnoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnoterActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new mark_note(chief_email).setVisible(true);
    }//GEN-LAST:event_btnnoterActionPerformed

    private void txtstageidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstageidKeyReleased
        // TODO add your handling code here:
        validchoose();
    }//GEN-LAST:event_txtstageidKeyReleased

    private void feltringKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_feltringKeyReleased
        // TODO add your handling code here:
        String name = feltring.getText();
        System.out.println(name);
        getcandidats("", name);

    }//GEN-LAST:event_feltringKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_formComponentShown

    private void stagessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stagessActionPerformed
        // TODO add your handling code here:
                String stage = (String) stagess.getSelectedItem();
        System.out.println(stage);
        getcandidats(stage, "");

    }//GEN-LAST:event_stagessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(espace_chiefstage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(espace_chiefstage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(espace_chiefstage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(espace_chiefstage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new espace_chiefstage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnchoose;
    private javax.swing.JButton btnnoter;
    private javax.swing.JButton btnout;
    private javax.swing.JTextField feltring;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> stagess;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txtduree;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtstageid;
    private javax.swing.JTextArea txtsujet;
    private javax.swing.JTextField txttitle;
    // End of variables declaration//GEN-END:variables
}
