/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appgestionstagaire;

import date_acces_object.user_date_acces;
import javax.swing.JOptionPane;
import module.hierarchy;
import module.person;
import module.responsable_stage;

/**
 *
 * @author User
 */
public class logIn extends javax.swing.JFrame {

    /**
     * Creates new form logIn
     */
    public logIn() {
        initComponents();
        // btnlogin.setEnabled(false);
         btnlogin.setEnabled(false);
    }
    public String mailsecurity = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";

    public void clear() {
        txtmail.setText("");
        txtpass.setText("");
        btnlogin.setEnabled(false);

    }

    public void inputverification() {
        String email = txtmail.getText();
        String pass = txtpass.getText();
        if (!email.isEmpty()  && !pass.isEmpty()) {
            btnlogin.setEnabled(true);
        } else {
            btnlogin.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        btnlogin = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnforget = new javax.swing.JButton();
        txtpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EMAIL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        txtmail.setBackground(new java.awt.Color(255, 255, 255));
        txtmail.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtmail.setForeground(new java.awt.Color(0, 0, 0));
        txtmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmailKeyReleased(evt);
            }
        });
        getContentPane().add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 251, -1));

        btnlogin.setBackground(new java.awt.Color(255, 204, 255));
        btnlogin.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(0, 0, 0));
        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginIcon.png"))); // NOI18N
        btnlogin.setText("logIn");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 110, 50));

        btnexit.setBackground(new java.awt.Color(255, 204, 255));
        btnexit.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnexit.setForeground(new java.awt.Color(0, 0, 0));
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnexit.setText("exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 110, 50));

        btnforget.setBackground(new java.awt.Color(255, 204, 255));
        btnforget.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnforget.setForeground(new java.awt.Color(0, 0, 0));
        btnforget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forgeticon.png"))); // NOI18N
        btnforget.setText("did u forget your password ?");
        btnforget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnforgetActionPerformed(evt);
            }
        });
        getContentPane().add(btnforget, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 260, 30));

        txtpass.setBackground(new java.awt.Color(255, 255, 255));
        txtpass.setForeground(new java.awt.Color(0, 0, 0));
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpassKeyReleased(evt);
            }
        });
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 250, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Log In1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        String email = txtmail.getText();
        String pass = txtpass.getText();
        person personne = user_date_acces.logIn(email, pass);
        if (personne != null) {

            JOptionPane.showMessageDialog(null, personne.getClass());
            if (personne.getClass().equals(hierarchy.class)) {
                // vers espase hirach

                this.setVisible(false);
                new espace_hera(email).setVisible(true);

            } else if (personne.getClass().equals(responsable_stage.class)) {
                // vers espase chef stage 
                this.setVisible(false);
                new espace_chiefstage(email).setVisible(true);
            }

        }


    }//GEN-LAST:event_btnloginActionPerformed


    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "do you wanna close this application", "select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            //user choose yes like a anwser

            System.exit(0);
        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void txtmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmailKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtmailKeyReleased

    private void btnforgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnforgetActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new forgetpass().setVisible(true);
    }//GEN-LAST:event_btnforgetActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void txtpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtpassKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnforget;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtmail;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
