/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appgestionstagaire;

import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.sql.ResultSet;
import date_acces_object.hira_date_acces;
import date_acces_object.operation;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class manage_candidat extends javax.swing.JFrame {

    /**
     * Creates new form manage_candidat
     */
    public manage_candidat() {
        initComponents();
        btnassign.setEnabled(false);
        btnprint.setEnabled(false);
        btncancel.setEnabled(false);

    }
    public String hiraemail;
    public String mailsecurity = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";

    public manage_candidat(String hiraemail) {
        initComponents();
        this.hiraemail = hiraemail;
        btnassign.setEnabled(false);
        btnprint.setEnabled(false);
        btncancel.setEnabled(false);

    }

    public void inputverification() {
        String cemail = txtemail.getText();
        String chiefmail = txtchief.getText();
        String nom = txtnom.getText();
        String prenom = txtprenom.getText();
        String id = txtidstage.getText();
        if (!cemail.isEmpty() && cemail.matches(mailsecurity) && !chiefmail.isEmpty() && !nom.isEmpty() && !prenom.isEmpty() && !id.isEmpty()) {
            btnassign.setEnabled(true);
            btnprint.setEnabled(true);
            btncancel.setEnabled(true);
        } else {
            btnassign.setEnabled(false);
            btnprint.setEnabled(false);
            btncancel.setEnabled(false);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        btncancel = new javax.swing.JButton();
        btnassign = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtchief = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtidstage = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 255));
        jLabel1.setText("FIRST NAME OF CANDIDAT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 116, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 255));
        jLabel2.setText("LAST NAME OF CANDIDAT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 159, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 255));
        jLabel3.setText("EMAIL OF CANDIDAT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 203, -1, 16));

        txtnom.setBackground(new java.awt.Color(255, 204, 255));
        txtnom.setForeground(new java.awt.Color(0, 0, 0));
        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnomKeyReleased(evt);
            }
        });
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 378, -1));

        txtprenom.setBackground(new java.awt.Color(255, 204, 255));
        txtprenom.setForeground(new java.awt.Color(0, 0, 0));
        txtprenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprenomKeyReleased(evt);
            }
        });
        getContentPane().add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 378, -1));

        txtemail.setBackground(new java.awt.Color(255, 204, 255));
        txtemail.setForeground(new java.awt.Color(0, 0, 0));
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 378, -1));

        btncancel.setBackground(new java.awt.Color(255, 204, 255));
        btncancel.setForeground(new java.awt.Color(0, 0, 0));
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btncancel.setText("cancel registration");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 237, -1));

        btnassign.setBackground(new java.awt.Color(255, 204, 255));
        btnassign.setForeground(new java.awt.Color(0, 0, 0));
        btnassign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/assign.png"))); // NOI18N
        btnassign.setText("assigned as a potential intern");
        btnassign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnassignActionPerformed(evt);
            }
        });
        getContentPane().add(btnassign, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 254, -1));

        btnprint.setBackground(new java.awt.Color(255, 204, 255));
        btnprint.setForeground(new java.awt.Color(0, 0, 0));
        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.png"))); // NOI18N
        btnprint.setText("print convention");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        getContentPane().add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 260, 50));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 255));
        jLabel5.setText("EMAIL OF stagechief");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 245, -1, -1));

        txtchief.setBackground(new java.awt.Color(255, 204, 255));
        txtchief.setForeground(new java.awt.Color(0, 0, 0));
        txtchief.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtchiefKeyReleased(evt);
            }
        });
        getContentPane().add(txtchief, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 248, 378, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 255));
        jLabel6.setText("ID  traineeship");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 288, -1, -1));

        txtidstage.setBackground(new java.awt.Color(255, 204, 255));
        txtidstage.setForeground(new java.awt.Color(0, 0, 0));
        txtidstage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidstageKeyReleased(evt);
            }
        });
        getContentPane().add(txtidstage, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 291, 378, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goback.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/managecandidat.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnassignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnassignActionPerformed
        // TODO add your handling code here:
        String nom = txtnom.getText();
        String chiefmail = txtchief.getText();
        String email = txtemail.getText();
        int id_stage = Integer.valueOf(txtidstage.getText());
        hira_date_acces.candidat_to_potensielCandidat(nom, email, hiraemail, chiefmail, id_stage);

    }//GEN-LAST:event_btnassignActionPerformed

    private void txtnomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtnomKeyReleased

    private void txtprenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprenomKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtprenomKeyReleased

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtemailKeyReleased

    private void txtchiefKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtchiefKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtchiefKeyReleased

    private void txtidstageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidstageKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtidstageKeyReleased

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
        boolean ispotentialcandidat = false;
        String nom = txtnom.getText();
        String email = txtemail.getText();
        String path = "C:\\Users\\User\\Documents\\NetBeansProjects\\APPGestionStagaire\\convantionsnosigne\\";
        String query = "select * from person where email='" + email + "' and nom = '" + nom + "'";

        try {
            ResultSet rs = operation.getdate(query);
            if (rs.next()) {
                ResultSet rs1 = operation.getdate("select * from candidat where id_person=" + rs.getInt("id"));
                if (rs1.next()) {
                    ispotentialcandidat = rs1.getBoolean("etat");

                    if (ispotentialcandidat) {

                        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
                        try {
                            PdfWriter.getInstance(doc, new FileOutputStream(path + "convantioN" + rs.getString("nom") + ".pdf"));
                            doc.open();
                            Paragraph catalogue = new Paragraph("                                                              convantion \n");
                            doc.add(catalogue);
                            Paragraph starline = new Paragraph("*******************************************************************************************************\n");
                            doc.add(starline);
                            Paragraph p3 = new Paragraph("\n Nom de l'entreprise: fsts \n");
                            Paragraph p33 = new Paragraph("\n Adresse de l'entreprise: boulevard Mohammed-V casa  \n");
                            Paragraph pr = new Paragraph("Mme/M. " + nom + " " + rs.getString("prenom") + " avec @mail :" + rs.getString("email") + " address : " + rs.getString("address") + " ");
                            doc.add(p3);
                            doc.add(p33);
                            doc.add(pr);
                            doc.add(starline);
                            Paragraph p4 = new Paragraph("signature du etablissement :    ");
                            doc.add(p4);
                            doc.add(starline);
                            JOptionPane.showMessageDialog(null, "pdf has been created");
                        } catch (DocumentException | FileNotFoundException e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                        doc.close();
                    } else {
                        JOptionPane.showMessageDialog(null, "this s not a potencial candidat ");
                    }

                }
            } else {
                JOptionPane.showMessageDialog(null, " candidat doesn't exist ");
            }
        } catch (SQLException ex) {
            Logger.getLogger(manage_candidat.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnprintActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        String nom = txtnom.getText();
        String chiefmail = txtchief.getText();
        String email = txtemail.getText();
        int id_stage = Integer.valueOf(txtidstage.getText());
        hira_date_acces.cancelregestiration(nom, email, hiraemail, chiefmail, id_stage);
    }//GEN-LAST:event_btncancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manage_candidat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manage_candidat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manage_candidat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manage_candidat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manage_candidat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnassign;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtchief;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtidstage;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    // End of variables declaration//GEN-END:variables
}
