/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appgestionstagaire;

import date_acces_object.hira_date_acces;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class manage_trainers extends javax.swing.JFrame {

    /**
     * Creates new form manage_trainers
     */
    public manage_trainers() {
        initComponents();
        btnsave.setEnabled(false);

    }

    public manage_trainers(String email) {
        initComponents();
        btnsave.setEnabled(false);

    }

    public void inputverification() {
        String cemail = txtemailc.getText();
        String nom = txtnom.getText();
        String daysoff = txtoffdays.getText();
        String datesend = txtdatesend.getText();
        String dateend = txtdateend.getText();
        String datedepart = txtdatedepart.getText();
        String filecon = txtconvention.getText();
        File doc = txtpath.getCurrentDirectory();
        String path = doc.getPath() + "\\" + filecon;
        if (!cemail.isEmpty() && !nom.isEmpty() && !daysoff.isEmpty() && !datesend.isEmpty() && !dateend.isEmpty() && !datedepart.isEmpty() && !filecon.isEmpty()) {
            btnsave.setEnabled(true);
        } else {
            btnsave.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtconvention = new javax.swing.JTextField();
        txtdatedepart = new javax.swing.JTextField();
        txtdatesend = new javax.swing.JTextField();
        txtdateend = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtoffdays = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        txtemailc = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        txtpath = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 255));
        jLabel1.setText("CONVENTION FILE NAME ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 255));
        jLabel2.setText("DATE SEND ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 255));
        jLabel3.setText("FIRST NAME CANDIDAT ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 255));
        jLabel4.setText("LAST NAME CANDIDAT");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 255));
        jLabel5.setText("EMAIL CANDIDAT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 255));
        jLabel6.setText("DATE of DEPARTURE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 255));
        jLabel7.setText("END DATE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 255));
        jLabel8.setText("NUMBER OF DAYS OFF");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        txtconvention.setBackground(new java.awt.Color(255, 204, 255));
        txtconvention.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtconvention, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 290, -1));

        txtdatedepart.setBackground(new java.awt.Color(255, 204, 255));
        txtdatedepart.setForeground(new java.awt.Color(0, 0, 0));
        txtdatedepart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdatedepartKeyReleased(evt);
            }
        });
        getContentPane().add(txtdatedepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 341, -1));

        txtdatesend.setBackground(new java.awt.Color(255, 204, 255));
        txtdatesend.setForeground(new java.awt.Color(0, 0, 0));
        txtdatesend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdatesendKeyReleased(evt);
            }
        });
        getContentPane().add(txtdatesend, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 290, -1));

        txtdateend.setBackground(new java.awt.Color(255, 204, 255));
        txtdateend.setForeground(new java.awt.Color(0, 0, 0));
        txtdateend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdateendKeyReleased(evt);
            }
        });
        getContentPane().add(txtdateend, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 341, -1));

        txtnom.setBackground(new java.awt.Color(255, 204, 255));
        txtnom.setForeground(new java.awt.Color(0, 0, 0));
        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnomKeyReleased(evt);
            }
        });
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 290, -1));

        txtoffdays.setBackground(new java.awt.Color(255, 204, 255));
        txtoffdays.setForeground(new java.awt.Color(0, 0, 0));
        txtoffdays.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtoffdaysKeyReleased(evt);
            }
        });
        getContentPane().add(txtoffdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 341, -1));

        jTextField7.setBackground(new java.awt.Color(255, 204, 255));
        jTextField7.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 290, -1));

        txtemailc.setBackground(new java.awt.Color(255, 204, 255));
        txtemailc.setForeground(new java.awt.Color(0, 0, 0));
        txtemailc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailcKeyReleased(evt);
            }
        });
        getContentPane().add(txtemailc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 290, -1));

        btnsave.setBackground(new java.awt.Color(255, 204, 255));
        btnsave.setForeground(new java.awt.Color(0, 0, 0));
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seve.png"))); // NOI18N
        btnsave.setText("save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 97, -1));

        txtpath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpathActionPerformed(evt);
            }
        });
        getContentPane().add(txtpath, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 360, 270));

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goback.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage intern1.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpathActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String cemail = txtemailc.getText();
        String nom = txtnom.getText();
        String daysoff = txtoffdays.getText();
        String datesend = txtdatesend.getText();
        String dateend = txtdateend.getText();
        String datedepart = txtdatedepart.getText();
        String filecon = txtconvention.getText();
        File doc = txtpath.getCurrentDirectory();
        String path = doc.getPath() + "\\" + filecon;
        System.out.println(path);
        if (new File(path).exists()) {
            hira_date_acces.saveIntern(cemail, nom, path, datesend, datedepart, Integer.valueOf(daysoff), dateend);
            txtemailc.setText("");
            txtnom.setText("");
            txtoffdays.setText("");
            txtdatesend.setText("");
            txtdateend.setText("");
            txtdatedepart.setText("");
            txtconvention.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "File doesn't exist in this directery ");
            txtconvention.setText("");

        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtdatesendKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdatesendKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtdatesendKeyReleased

    private void txtnomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtnomKeyReleased

    private void txtemailcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailcKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtemailcKeyReleased

    private void txtdatedepartKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdatedepartKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtdatedepartKeyReleased

    private void txtdateendKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdateendKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtdateendKeyReleased

    private void txtoffdaysKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoffdaysKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtoffdaysKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manage_trainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manage_trainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manage_trainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manage_trainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manage_trainers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField txtconvention;
    private javax.swing.JTextField txtdatedepart;
    private javax.swing.JTextField txtdateend;
    private javax.swing.JTextField txtdatesend;
    private javax.swing.JTextField txtemailc;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtoffdays;
    private javax.swing.JFileChooser txtpath;
    // End of variables declaration//GEN-END:variables
}
