/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appgestionstagaire;

import date_acces_object.chief_data_acces;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import module.stagaire;

/**
 *
 * @author User
 */
public class mark_note extends javax.swing.JFrame {

    /**
     * Creates new form mark_note
     */
    String cemail;

    public mark_note() {
        initComponents();
        System.out.println("11111111111111111");
    }

    public mark_note(String mail) {
        initComponents();
        cemail = mail;
        btnsave.setEnabled(false);
        txtnom.setEditable(false);
        txtprenom.setEditable(false);
        getstagaires(mail);
        
    }

    public void validate() {
        String nom = txtnom.getText();
        String prenom = txtprenom.getText();
        String t = txttravail.getText();
        String com = txtcomp.getText();
        String r = txtra.getText();
        if (!nom.isEmpty() && !prenom.isEmpty() && !t.isEmpty() && !com.isEmpty() && !r.isEmpty()) {
            btnsave.setEnabled(true);
        } else {
            btnsave.setEnabled(false);
        }

    }

    public void getstagaires(String email) {
        DefaultTableModel df = (DefaultTableModel) tab.getModel();
        df.setRowCount(0);
        ArrayList<stagaire> stgs = chief_data_acces.getstagaires(email);
        if(!stgs.isEmpty()){
        for(stagaire el : stgs){
        Vector v = new Vector();
        v.add(el.getNom());
        v.add(el.getPrenom());
        v.add(el.getS().getTitle());
        df.addRow(v);
        
        }
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        stagetype = new javax.swing.JComboBox<>();
        feltring = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txttravail = new javax.swing.JTextField();
        txtcomp = new javax.swing.JTextField();
        txtra = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "first name", "last name", "intreship "
            }
        ));
        jScrollPane1.setViewportView(tab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 115, -1, 396));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goback.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 34, -1, -1));

        getContentPane().add(stagetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 75, 86, -1));
        getContentPane().add(feltring, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 75, 97, -1));

        jLabel1.setText("feltring by name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 78, -1, -1));

        jLabel2.setText("first name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 131, -1, -1));

        jLabel3.setText("last name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 175, -1, -1));

        jLabel4.setText("mark work");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));

        jLabel5.setText("mark behavior");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 265, -1, -1));

        jLabel6.setText("mark report");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 307, -1, -1));

        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnomKeyReleased(evt);
            }
        });
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 128, 149, -1));

        txtprenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprenomKeyReleased(evt);
            }
        });
        getContentPane().add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 172, 149, -1));

        txttravail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttravailKeyReleased(evt);
            }
        });
        getContentPane().add(txttravail, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 217, 149, -1));

        txtcomp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcompKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcompKeyTyped(evt);
            }
        });
        getContentPane().add(txtcomp, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 262, 149, -1));

        txtra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtraKeyReleased(evt);
            }
        });
        getContentPane().add(txtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 304, 149, -1));

        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seve.png"))); // NOI18N
        btnsave.setText("save");
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 393, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new espace_chiefstage(cemail).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyReleased
        // TODO add your handling code here:
        validate();
    }//GEN-LAST:event_txtnomKeyReleased

    private void txtprenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprenomKeyReleased
        // TODO add your handling code here:
        validate();

    }//GEN-LAST:event_txtprenomKeyReleased

    private void txttravailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttravailKeyReleased
        // TODO add your handling code here:
        validate();

    }//GEN-LAST:event_txttravailKeyReleased

    private void txtcompKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcompKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcompKeyTyped

    private void txtcompKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcompKeyReleased
        // TODO add your handling code here:
        validate();

    }//GEN-LAST:event_txtcompKeyReleased

    private void txtraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtraKeyReleased
        // TODO add your handling code here:
        validate();

    }//GEN-LAST:event_txtraKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mark_note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mark_note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mark_note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mark_note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mark_note().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JTextField feltring;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> stagetype;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txtcomp;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtra;
    private javax.swing.JTextField txttravail;
    // End of variables declaration//GEN-END:variables
}
