/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appgestionstagaire;

import date_acces_object.hira_date_acces;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class regestirationtrainers extends javax.swing.JFrame {

    /**
     * Creates new form regestirationtrainers
     */
    public regestirationtrainers() {
        initComponents();
        btnsave.setEnabled(false);
    }

    public String mailsecurity = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";

    public void inputverification() {
        String email = txtemail.getText();
        String nom = txtnom.getText();
        String prenom = txtprenom.getText();
        String mobile = txtmobile.getText();
        File doccv;
        doccv = cv.getCurrentDirectory();
        String datedebut = txtdate.getText();
        String filename = txtfilename.getText();
        String add = txtadd.getText();
        String id1 = txtid1.getText();
        String id2 = txtid2.getText();
        String id3 = txtid3.getText();

        if (!email.isEmpty() && email.matches(mailsecurity) && !prenom.isEmpty() && !mobile.isEmpty() && !datedebut.isEmpty() && doccv.exists() && !add.isEmpty() && !filename.isEmpty()) {
            if (!id1.isEmpty() || !id2.isEmpty() || !id3.isEmpty()) {
                btnsave.setEnabled(true);
            }

        } else {
            btnsave.setEnabled(false);
        }

    }

    public void clear() {
        txtnom.setText("");
        txtprenom.setText("");
        txtadd.setText("");
        txtmobile.setText("");
        txtdate.setText("");
        txtemail.setText("");
        txtfilename.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        cv = new javax.swing.JFileChooser();
        txtdate = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtadd = new javax.swing.JTextField();
        txtfilename = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtid1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtid2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtid3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 255));
        jLabel1.setText("FIRST NAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 255));
        jLabel2.setText("LAST NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 255));
        jLabel3.setText("MOBILE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 255));
        jLabel4.setText("EMAIL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 255));
        jLabel5.setText("file path");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 255));
        jLabel6.setText("START DATE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        txtnom.setBackground(new java.awt.Color(255, 204, 255));
        txtnom.setForeground(new java.awt.Color(0, 0, 0));
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnomKeyReleased(evt);
            }
        });
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 200, -1));

        txtprenom.setBackground(new java.awt.Color(255, 204, 255));
        txtprenom.setForeground(new java.awt.Color(0, 0, 0));
        txtprenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomActionPerformed(evt);
            }
        });
        txtprenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprenomKeyReleased(evt);
            }
        });
        getContentPane().add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, -1));

        txtmobile.setBackground(new java.awt.Color(255, 204, 255));
        txtmobile.setForeground(new java.awt.Color(0, 0, 0));
        txtmobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmobileKeyReleased(evt);
            }
        });
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 200, -1));

        txtemail.setBackground(new java.awt.Color(255, 204, 255));
        txtemail.setForeground(new java.awt.Color(0, 0, 0));
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 200, -1));

        cv.setBackground(new java.awt.Color(255, 204, 255));
        cv.setForeground(new java.awt.Color(255, 255, 255));
        cv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvActionPerformed(evt);
            }
        });
        getContentPane().add(cv, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 270, 370));

        txtdate.setBackground(new java.awt.Color(255, 204, 255));
        txtdate.setForeground(new java.awt.Color(0, 0, 0));
        txtdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdateKeyReleased(evt);
            }
        });
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 200, -1));

        btnsave.setBackground(new java.awt.Color(255, 204, 255));
        btnsave.setForeground(new java.awt.Color(0, 0, 0));
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seve.png"))); // NOI18N
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 578, 124, 30));

        btnexit.setBackground(new java.awt.Color(255, 204, 255));
        btnexit.setForeground(new java.awt.Color(0, 0, 0));
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 581, 104, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 255));
        jLabel7.setText("ADDRESS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        txtadd.setBackground(new java.awt.Color(255, 204, 255));
        txtadd.setForeground(new java.awt.Color(0, 0, 0));
        txtadd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtaddKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaddKeyTyped(evt);
            }
        });
        getContentPane().add(txtadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 200, -1));

        txtfilename.setBackground(new java.awt.Color(255, 204, 255));
        txtfilename.setForeground(new java.awt.Color(0, 0, 0));
        txtfilename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfilenameKeyReleased(evt);
            }
        });
        getContentPane().add(txtfilename, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 200, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 255));
        jLabel8.setText("FILE NAME");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 255));
        jLabel10.setText("stage id1");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 224, -1, -1));

        txtid1.setBackground(new java.awt.Color(255, 204, 255));
        txtid1.setForeground(new java.awt.Color(0, 0, 0));
        txtid1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtid1KeyReleased(evt);
            }
        });
        getContentPane().add(txtid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 250, 204, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 255));
        jLabel9.setText("stage id2");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 280, -1, -1));

        txtid2.setBackground(new java.awt.Color(255, 204, 255));
        txtid2.setForeground(new java.awt.Color(0, 0, 0));
        txtid2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtid2KeyReleased(evt);
            }
        });
        getContentPane().add(txtid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 310, 204, -1));

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 255));
        jLabel11.setText("stage id3");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 340, -1, -1));

        txtid3.setBackground(new java.awt.Color(255, 204, 255));
        txtid3.setForeground(new java.awt.Color(0, 0, 0));
        txtid3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtid3KeyReleased(evt);
            }
        });
        getContentPane().add(txtid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 370, 204, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goback.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inscription stagaires.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtprenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "do you wanna close this application", "select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            //user choose yes like a anwser

            System.exit(0);
        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void txtnomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtnomKeyReleased

    private void txtprenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprenomKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtprenomKeyReleased

    private void txtmobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobileKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtmobileKeyReleased

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtemailKeyReleased

    private void txtdateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdateKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtdateKeyReleased

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        File doc = cv.getCurrentDirectory();
        String nom = txtnom.getText();
        String prenom = txtprenom.getText();
        String add = txtadd.getText();
        String mobile = txtmobile.getText();
        String date = txtdate.getText();
        String email = txtemail.getText();
        String path = doc.getPath();
        String filename = txtfilename.getText();
        String id1 = txtid1.getText();
        String id2 = txtid2.getText();
        String id3 = txtid3.getText();
        ArrayList<Integer> stagepostuler = new ArrayList<>(3);
        if (!id1.isEmpty() ) stagepostuler.add(Integer.valueOf(id1));
        if (!id2.isEmpty()) stagepostuler.add(Integer.valueOf(id2));
        if (!id3.isEmpty()) stagepostuler.add(Integer.valueOf(id3));

        if (new File(path + "\\" + filename).exists()) {
            
            try {
                hira_date_acces.save(nom, prenom, email, mobile, path + "\\" + filename, date, add, stagepostuler);
                clear();

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "this file doessn't exist in this directory");
        }


    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtaddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaddKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddKeyTyped

    private void txtaddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaddKeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtaddKeyReleased

    private void cvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvActionPerformed

    private void txtfilenameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfilenameKeyReleased
        // TODO add your handling code here:
        inputverification();

    }//GEN-LAST:event_txtfilenameKeyReleased

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtid1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtid1KeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtid1KeyReleased

    private void txtid2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtid2KeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtid2KeyReleased

    private void txtid3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtid3KeyReleased
        // TODO add your handling code here:
        inputverification();
    }//GEN-LAST:event_txtid3KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regestirationtrainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regestirationtrainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regestirationtrainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regestirationtrainers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regestirationtrainers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnsave;
    private javax.swing.JFileChooser cv;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtadd;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfilename;
    private javax.swing.JTextField txtid1;
    private javax.swing.JTextField txtid2;
    private javax.swing.JTextField txtid3;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    // End of variables declaration//GEN-END:variables
}
